"""empty message

Revision ID: 3142eb6b73c6
Revises: 
Create Date: 2017-05-19 15:45:35.826733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3142eb6b73c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('height', sa.String(length=80), nullable=True),
    sa.Column('profile_photo', sa.String(length=80), nullable=True),
    sa.Column('date_created', sa.String(length=30), nullable=True),
    sa.Column('bio', sa.String(length=250), nullable=True),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.Column('origin', sa.String(length=80), nullable=True),
    sa.Column('professional', sa.String(length=80), nullable=True),
    sa.Column('school', sa.String(length=80), nullable=True),
    sa.Column('userrel', sa.String(length=80), nullable=True),
    sa.Column('userrelty', sa.String(length=80), nullable=True),
    sa.Column('honesty', sa.String(length=80), nullable=True),
    sa.Column('firendly', sa.String(length=80), nullable=True),
    sa.Column('loyalty', sa.String(length=80), nullable=True),
    sa.Column('integrity', sa.String(length=80), nullable=True),
    sa.Column('respectful', sa.String(length=80), nullable=True),
    sa.Column('compassionate', sa.String(length=80), nullable=True),
    sa.Column('fair', sa.String(length=80), nullable=True),
    sa.Column('forgiving', sa.String(length=80), nullable=True),
    sa.Column('courageous', sa.String(length=80), nullable=True),
    sa.Column('generous', sa.String(length=80), nullable=True),
    sa.Column('polite', sa.String(length=80), nullable=True),
    sa.Column('kind', sa.String(length=80), nullable=True),
    sa.Column('loving', sa.String(length=80), nullable=True),
    sa.Column('optimistic', sa.String(length=80), nullable=True),
    sa.Column('reliable', sa.String(length=80), nullable=True),
    sa.Column('conscious', sa.String(length=80), nullable=True),
    sa.Column('f', sa.String(length=80), nullable=True),
    sa.Column('c', sa.String(length=80), nullable=True),
    sa.Column('r1', sa.String(length=80), nullable=True),
    sa.Column('a', sa.String(length=80), nullable=True),
    sa.Column('traveling', sa.String(length=80), nullable=True),
    sa.Column('food', sa.String(length=80), nullable=True),
    sa.Column('sports', sa.String(length=80), nullable=True),
    sa.Column('movies', sa.String(length=80), nullable=True),
    sa.Column('exercsing', sa.String(length=80), nullable=True),
    sa.Column('shopping', sa.String(length=80), nullable=True),
    sa.Column('music', sa.String(length=80), nullable=True),
    sa.Column('singing', sa.String(length=80), nullable=True),
    sa.Column('dancing', sa.String(length=80), nullable=True),
    sa.Column('reading', sa.String(length=80), nullable=True),
    sa.Column('fashion', sa.String(length=80), nullable=True),
    sa.Column('pets', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('person_id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
