"""empty message

Revision ID: 9306ee41b6ed
Revises: 3142eb6b73c6
Create Date: 2017-05-19 16:19:49.199410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9306ee41b6ed'
down_revision = '3142eb6b73c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('seeking_compassionate', sa.String(length=80), nullable=True))
    op.add_column('users', sa.Column('seeking_conscious', sa.String(length=80), nullable=True))
    op.add_column('users', sa.Column('seeking_courageous', sa.String(length=80), nullable=True))
    op.add_column('users', sa.Column('seeking_fair', sa.String(length=80), nullable=True))
    op.add_column('users', sa.Column('seeking_firendly', sa.String(length=80), nullable=True))
    op.add_column('users', sa.Column('seeking_forgiving', sa.String(length=80), nullable=True))
    op.add_column('users', sa.Column('seeking_generous', sa.String(length=80), nullable=True))
    op.add_column('users', sa.Column('seeking_honesty', sa.String(length=80), nullable=True))
    op.add_column('users', sa.Column('seeking_integrity', sa.String(length=80), nullable=True))
    op.add_column('users', sa.Column('seeking_kind', sa.String(length=80), nullable=True))
    op.add_column('users', sa.Column('seeking_loving', sa.String(length=80), nullable=True))
    op.add_column('users', sa.Column('seeking_loyalty', sa.String(length=80), nullable=True))
    op.add_column('users', sa.Column('seeking_optimistic', sa.String(length=80), nullable=True))
    op.add_column('users', sa.Column('seeking_polite', sa.String(length=80), nullable=True))
    op.add_column('users', sa.Column('seeking_reliable', sa.String(length=80), nullable=True))
    op.add_column('users', sa.Column('seeking_respectful', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'seeking_respectful')
    op.drop_column('users', 'seeking_reliable')
    op.drop_column('users', 'seeking_polite')
    op.drop_column('users', 'seeking_optimistic')
    op.drop_column('users', 'seeking_loyalty')
    op.drop_column('users', 'seeking_loving')
    op.drop_column('users', 'seeking_kind')
    op.drop_column('users', 'seeking_integrity')
    op.drop_column('users', 'seeking_honesty')
    op.drop_column('users', 'seeking_generous')
    op.drop_column('users', 'seeking_forgiving')
    op.drop_column('users', 'seeking_firendly')
    op.drop_column('users', 'seeking_fair')
    op.drop_column('users', 'seeking_courageous')
    op.drop_column('users', 'seeking_conscious')
    op.drop_column('users', 'seeking_compassionate')
    # ### end Alembic commands ###
